"""The learner's workspace: discovery, paths, config, subjects and data files.

Discovery order:
  1. the ``--workspace PATH`` flag;
  2. the environment variable ``INDELIBLE_WORKSPACE``;
  3. walking up from the current folder (at most 4 levels) for ``indelible.json``;
  4. the path stored in ``~/.indelible/workspace``.

A flag or environment path must name the workspace root itself (the folder
holding ``indelible.json``); it is never walked up from.

Usage in a command handler::

    from lib import ws as wsmod
    ws = wsmod.from_args(args)             # raises NoWorkspace (exit 2)
    subj = ws.resolve_subject(args.subject)
    with ws.lock():
        errors = subj.load_errors()
        ...
        subj.save_errors(errors)
"""

import os
import re
from pathlib import Path

from lib import NoWorkspace, UsageError, DataError, WORKSPACE_ASSETS
from lib import io as fio

MAX_WALK_UP = 4
ENV_WORKSPACE = "INDELIBLE_WORKSPACE"
CONFIG_NAME = "indelible.json"
MARK_BEGIN = "<!-- indelible:begin -->"
MARK_END = "<!-- indelible:end -->"
GENERATED_BANNER = "<!-- generated by indelible; do not edit -->"

SUBJECT_ID_RE = re.compile(r"^[a-z](?:[a-z0-9-]{0,30}[a-z0-9])?$")
RESERVED_SUBJECT_IDS = {
    "all", "root", "plan", "views", "reviews", "inbox", "archive", "data", "notes",
    "sheets", "scans", "answers", "ledger", "indelible", "none",
}

ROOT_DIRS = ["plan", "plan/ics", "views", "reviews", "inbox", ".indelible", ".indelible/backups"]
SUBJECT_DIRS = [
    "data", "views", "notes", "sheets", "scans", "answers", "archive",
    ".indelible", ".indelible/specs", ".indelible/keys", ".indelible/keys/errors", ".indelible/tmp",
]


# --------------------------------------------------------------------------
# Discovery
# --------------------------------------------------------------------------

def pointer_file():
    """``~/.indelible/workspace`` (honours HOME / USERPROFILE)."""
    return Path(os.path.expanduser("~")) / ".indelible" / "workspace"


def _root_at_or_above(path, max_up=MAX_WALK_UP):
    p = Path(path).expanduser()
    try:
        p = p.resolve()
    except OSError:
        return None
    for _ in range(max_up + 1):
        if (p / CONFIG_NAME).is_file():
            return p
        if p.parent == p:
            break
        p = p.parent
    return None


def read_pointer(pointer=None):
    pf = Path(pointer) if pointer is not None else pointer_file()
    try:
        text = fio.read_text(pf)
    except OSError:
        return None
    if not text:
        return None
    for line in text.split("\n"):
        if line.strip():
            return Path(line.strip()).expanduser()
    return None


def discover(flag=None, environ=None, cwd=None, pointer=None):
    """Find the workspace root. Returns ``(path or None, source, detail)``.

    ``source`` is one of ``flag``, ``env``, ``cwd``, ``pointer`` or ``none``.
    An explicit flag or environment path that holds no workspace is not
    passed over: it returns ``(None, "flag"|"env", detail)``.
    """
    if flag:
        root = _root_at_or_above(flag, max_up=0)
        if root:
            return root, "flag", str(flag)
        return None, "flag", "--workspace %s holds no indelible.json" % flag
    if environ is None:
        env_path = os.environ.get("INDELIBLE_WORKSPACE")
    else:
        env_path = environ.get(ENV_WORKSPACE)
    if env_path:
        root = _root_at_or_above(env_path, max_up=0)
        if root:
            return root, "env", env_path
        return None, "env", "%s=%s holds no indelible.json" % (ENV_WORKSPACE, env_path)
    start = Path(cwd) if cwd is not None else Path.cwd()
    root = _root_at_or_above(start, MAX_WALK_UP)
    if root:
        return root, "cwd", str(start)
    ptr = read_pointer(pointer)
    if ptr is not None and (ptr / CONFIG_NAME).is_file():
        return ptr.resolve(), "pointer", str(ptr)
    return None, "none", None


def find_workspace(flag=None, environ=None, cwd=None, pointer=None):
    """The workspace root Path, or None."""
    return discover(flag, environ, cwd, pointer)[0]


def open_workspace(flag=None, required=True):
    root, source, detail = discover(flag)
    if root is None:
        if required:
            raise NoWorkspace(detail if source in ("flag", "env") else None)
        return None
    return Workspace(root)


def from_args(args, required=True):
    """The Workspace for a parsed argparse namespace (uses ``args.workspace``)."""
    return open_workspace(getattr(args, "workspace", None), required=required)


require = from_args


# --------------------------------------------------------------------------
# IDs
# --------------------------------------------------------------------------

def max_seq(ids, pattern):
    """Largest integer captured by ``pattern`` (group 1) among ids; 0 if none."""
    rx = re.compile(pattern) if isinstance(pattern, str) else pattern
    best = 0
    for i in ids:
        if not isinstance(i, str):
            continue
        m = rx.match(i)
        if m:
            best = max(best, int(m.group(1)))
    return best


def _ids_in(rows, *fields):
    out = []
    for r in rows:
        for f in fields:
            v = r.get(f)
            if isinstance(v, str):
                out.append(v)
    return out


# --------------------------------------------------------------------------
# Marked sections (CLAUDE.md generated parts)
# --------------------------------------------------------------------------

def replace_marked_section(text, inner):
    """Replace what lies between the begin/end markers (appending them if absent)."""
    inner = inner.rstrip("\n")
    b, e = text.find(MARK_BEGIN), text.find(MARK_END)
    if b == -1 or e == -1 or e < b:
        sep = "" if text.endswith("\n") or not text else "\n"
        return text + sep + MARK_BEGIN + "\n" + inner + "\n" + MARK_END + "\n"
    return text[: b + len(MARK_BEGIN)] + "\n" + inner + "\n" + text[e:]


def marked_section(text):
    """What lies between the markers, or None."""
    b, e = text.find(MARK_BEGIN), text.find(MARK_END)
    if b == -1 or e == -1 or e < b:
        return None
    return text[b + len(MARK_BEGIN): e].strip("\n")


# --------------------------------------------------------------------------
# Workspace
# --------------------------------------------------------------------------

class Workspace(object):
    """The learner's study folder."""

    def __init__(self, root):
        self.root = Path(root).expanduser().resolve()
        self._config = None

    def __repr__(self):
        return "Workspace(%r)" % str(self.root)

    # ---- paths ------------------------------------------------------------
    @property
    def config_path(self):
        return self.root / CONFIG_NAME

    @property
    def claude_md(self):
        return self.root / "CLAUDE.md"

    @property
    def ledger_path(self):
        return self.root / "ledger.jsonl"

    @property
    def plan_dir(self):
        return self.root / "plan"

    @property
    def blocks_path(self):
        return self.root / "plan" / "blocks.jsonl"

    @property
    def ics_dir(self):
        return self.root / "plan" / "ics"

    @property
    def views_dir(self):
        return self.root / "views"

    @property
    def week_view_path(self):
        return self.root / "views" / "week.md"

    @property
    def reviews_dir(self):
        return self.root / "reviews"

    @property
    def inbox_dir(self):
        return self.root / "inbox"

    @property
    def archive_dir(self):
        return self.root / "archive"

    @property
    def state_dir(self):
        return self.root / ".indelible"

    @property
    def lock_path(self):
        return self.state_dir / "write.lock"

    @property
    def quarantine_path(self):
        return self.state_dir / "quarantine.jsonl"

    @property
    def render_state_path(self):
        return self.state_dir / "render.json"

    @property
    def backups_dir(self):
        return self.state_dir / "backups"

    def rel(self, path):
        """Workspace-relative POSIX path."""
        try:
            return Path(path).resolve().relative_to(self.root).as_posix()
        except ValueError:
            return Path(path).as_posix()

    def ensure_tree(self):
        for d in ROOT_DIRS:
            fio.ensure_dir(self.root / d)

    # ---- locking and reading ---------------------------------------------
    def lock(self, timeout=3.0):
        """The workspace write lock (a context manager)."""
        return fio.write_lock(self.root, timeout=timeout)

    def read_jsonl(self, path):
        return fio.read_jsonl(path, ws_root=self.root)

    def quarantine_rows(self):
        return fio.read_quarantine(self.root)

    def quarantine_count(self):
        return fio.quarantine_count(self.root)

    # ---- config -----------------------------------------------------------
    def load_config(self, reload=False):
        if self._config is None or reload:
            cfg = fio.read_json(self.config_path)
            if not isinstance(cfg, dict):
                raise DataError("%s is empty or not a JSON object" % self.config_path)
            self._config = cfg
        return self._config

    config = property(lambda self: self.load_config())

    def save_config(self, cfg):
        fio.write_json(self.config_path, cfg)
        self._config = cfg

    def timezone(self):
        return self.load_config().get("timezone")

    def tzinfo(self):
        """The workspace time zone (see ``dates.tz_for`` for the fallback)."""
        from lib import dates
        try:
            name = self.timezone()
        except (DataError, OSError):
            name = None
        return dates.tz_for(name)

    def now(self):
        """The current time in the workspace time zone: the one clock every command uses."""
        from lib import dates
        return dates.now().astimezone(self.tzinfo())

    def today(self):
        """Today's date in the workspace time zone."""
        return self.now().date()

    def schedule_mode(self):
        return (self.load_config().get("time") or {}).get("schedule", "scheduled")

    # ---- subjects ---------------------------------------------------------
    def subject_entries(self, states=None):
        subs = self.load_config().get("subjects") or []
        out = [s for s in subs if isinstance(s, dict) and s.get("id")]
        if states:
            wanted = set([states] if isinstance(states, str) else states)
            out = [s for s in out if s.get("state", "live") in wanted]
        return out

    def subject_entry(self, sid):
        for s in self.subject_entries():
            if s.get("id") == sid:
                return s
        return None

    def subject_ids(self, states=None):
        return [s["id"] for s in self.subject_entries(states)]

    def live_subject_ids(self):
        return self.subject_ids("live")

    def subject(self, sid):
        entry = self.subject_entry(sid)
        if entry is None:
            known = ", ".join(self.subject_ids()) or "none yet"
            raise UsageError("Unknown subject '%s'. Subjects: %s" % (sid, known))
        return Subject(self, entry["id"], entry.get("dir") or entry["id"])

    def subjects(self, states=None):
        return [Subject(self, s["id"], s.get("dir") or s["id"]) for s in self.subject_entries(states)]

    def subject_from_cwd(self, cwd=None):
        here = Path(cwd) if cwd is not None else Path.cwd()
        try:
            rel = here.resolve().relative_to(self.root)
        except (ValueError, OSError):
            return None
        if not rel.parts:
            return None
        first = rel.parts[0]
        for s in self.subject_entries():
            if (s.get("dir") or s["id"]) == first:
                return Subject(self, s["id"], s.get("dir") or s["id"])
        return None

    def resolve_subject(self, arg=None, cwd=None):
        """Subject from an argument, else the cwd, else the only live subject."""
        if arg:
            return self.subject(arg)
        subj = self.subject_from_cwd(cwd)
        if subj is not None:
            return subj
        live = self.live_subject_ids()
        if len(live) == 1:
            return self.subject(live[0])
        if not live:
            raise UsageError(
                "No live subjects yet. Run: indelible.py subject add <id> --title <title> --profile <profile>"
            )
        raise UsageError("Which subject? Pass one of: %s" % ", ".join(live))

    # ---- ledger (append) ---------------------------------------------------
    def load_ledger(self, include_archive=False):
        rows = self.read_jsonl(self.ledger_path)
        if include_archive:
            for p in sorted(self.archive_dir.glob("ledger-*.jsonl")):
                rows = self.read_jsonl(p) + rows
        return rows

    def append_ledger(self, row):
        return fio.append_jsonl(self.ledger_path, row)

    def ledger_status(self, rows=None):
        """ref -> latest status event row (the latest ``status`` event wins)."""
        rows = self.load_ledger() if rows is None else rows
        out = {}
        for r in rows:
            if r.get("kind") == "status" and r.get("ref"):
                out[r["ref"]] = r
        return out

    def open_ledger_items(self, kind=None, subject=None, rows=None):
        """Ledger items (not status events) whose latest status is open or none."""
        rows = self.load_ledger() if rows is None else rows
        status = self.ledger_status(rows)
        out = []
        for r in rows:
            if r.get("kind") == "status" or not r.get("id"):
                continue
            if kind and r.get("kind") != kind:
                continue
            if subject and r.get("subject") not in (subject, None):
                continue
            st = status.get(r["id"])
            if st and st.get("status") not in (None, "open"):
                continue
            out.append(r)
        return out

    def next_ledger_id(self):
        ids = _ids_in(self.load_ledger(include_archive=True), "id", "ref")
        return "L-%04d" % (max_seq(ids, r"^L-(\d+)$") + 1)

    # ---- plan blocks (snapshot) --------------------------------------------
    def load_blocks(self, include_archive=False):
        rows = self.read_jsonl(self.blocks_path)
        if include_archive:
            for p in sorted((self.plan_dir / "archive").glob("*.jsonl")):
                rows = self.read_jsonl(p) + rows
        return rows

    def save_blocks(self, rows):
        return fio.write_jsonl(self.blocks_path, rows)

    def get_block(self, block_id):
        for b in self.load_blocks():
            if b.get("id") == block_id:
                return b
        return None

    def next_block_id(self, subject_id, day, taken=None):
        """``B-YYYYMMDD-<subject>-N`` for the given date (N = 1 + max seen)."""
        from lib import dates
        stamp = dates.to_date(day).strftime("%Y%m%d")
        ids = _ids_in(self.load_blocks(include_archive=True), "id", "pair")
        ids += list(taken or [])
        rx = r"^B-%s-%s-(\d+)$" % (stamp, re.escape(subject_id))
        return "B-%s-%s-%d" % (stamp, subject_id, max_seq(ids, rx) + 1)

    # ---- render state ------------------------------------------------------
    def load_render_state(self):
        return fio.read_json(self.render_state_path, default={}) or {}

    def save_render_state(self, data):
        return fio.write_json(self.render_state_path, data)


# --------------------------------------------------------------------------
# Subject
# --------------------------------------------------------------------------

class Subject(object):
    """One subject folder inside the workspace."""

    def __init__(self, ws, sid, dirname=None):
        self.ws = ws
        self.id = sid
        self.dirname = dirname or sid
        self.root = ws.root / self.dirname
        self._cfg = None

    def __repr__(self):
        return "Subject(%r)" % self.id

    # ---- paths ------------------------------------------------------------
    json_path = property(lambda self: self.root / "subject.json")
    claude_md = property(lambda self: self.root / "CLAUDE.md")
    data_dir = property(lambda self: self.root / "data")
    sessions_path = property(lambda self: self.data_dir / "sessions.jsonl")
    attempts_path = property(lambda self: self.data_dir / "attempts.jsonl")
    exposures_path = property(lambda self: self.data_dir / "exposures.jsonl")
    errors_path = property(lambda self: self.data_dir / "errors.jsonl")
    sheets_path = property(lambda self: self.data_dir / "sheets.jsonl")
    topics_path = property(lambda self: self.data_dir / "topics.json")
    glossary_path = property(lambda self: self.data_dir / "glossary.jsonl")
    views_dir = property(lambda self: self.root / "views")
    notes_dir = property(lambda self: self.root / "notes")
    sheets_dir = property(lambda self: self.root / "sheets")
    scans_dir = property(lambda self: self.root / "scans")
    scans_index_path = property(lambda self: self.root / "scans" / "index.jsonl")
    answers_dir = property(lambda self: self.root / "answers")
    archive_dir = property(lambda self: self.root / "archive")
    state_dir = property(lambda self: self.root / ".indelible")
    session_lock_path = property(lambda self: self.state_dir / "session.lock")
    unclosed_path = property(lambda self: self.state_dir / "unclosed")
    specs_dir = property(lambda self: self.state_dir / "specs")
    keys_dir = property(lambda self: self.state_dir / "keys")
    key_errors_dir = property(lambda self: self.state_dir / "keys" / "errors")
    keys_opened_path = property(lambda self: self.state_dir / "keys" / "opened.jsonl")
    tmp_dir = property(lambda self: self.state_dir / "tmp")

    def spec_path(self, sheet_id):
        """The sealed visible spec: ``.indelible/specs/<id>.json``."""
        return self.specs_dir / ("%s.json" % sheet_id)

    def tmp_spec_path(self, sheet_id):
        """Where the builder writes a spec: ``.indelible/tmp/<id>.spec.json``."""
        return self.tmp_dir / ("%s.spec.json" % sheet_id)

    def tmp_answers_path(self, sheet_id):
        """Where the builder writes answers: ``.indelible/tmp/<id>.answers.json``."""
        return self.tmp_dir / ("%s.answers.json" % sheet_id)

    def typed_answers_path(self, sheet_id):
        """The learner's typed answers: ``answers/<id>.txt``."""
        return self.answers_dir / ("%s.txt" % sheet_id)

    def view_path(self, name):
        """``views/<name>`` (e.g. brief.md, progress.md, errors.md, log.md)."""
        return self.views_dir / name

    def notes_path(self, name):
        """``notes/<name>.md`` (append-only)."""
        return self.notes_dir / ("%s.md" % name)

    def key_path(self, sheet_id):
        return self.keys_dir / ("%s.json" % sheet_id)

    def error_key_path(self, error_id):
        return self.key_errors_dir / ("%s.json" % error_id)

    def sheet_month_dir(self, day):
        from lib import dates
        return self.sheets_dir / dates.to_date(day).strftime("%Y-%m")

    def rel(self, path):
        return self.ws.rel(path)

    def ensure_tree(self):
        for d in SUBJECT_DIRS:
            fio.ensure_dir(self.root / d)
        try:
            os.chmod(str(self.keys_dir), 0o700)
        except OSError:
            pass

    # ---- subject.json -------------------------------------------------------
    def load(self, reload=False):
        if self._cfg is None or reload:
            cfg = fio.read_json(self.json_path)
            if not isinstance(cfg, dict):
                raise DataError("%s is missing or not a JSON object" % self.json_path)
            self._cfg = cfg
        return self._cfg

    config = property(lambda self: self.load())

    def save(self, cfg):
        fio.write_json(self.json_path, cfg)
        self._cfg = cfg

    def title(self):
        return self.load().get("title") or self.id

    def profile(self):
        return self.load().get("profile")

    def target_date(self):
        from lib import dates
        d = (self.load().get("target") or {}).get("date")
        try:
            return dates.to_date(d) if d else None
        except ValueError:
            return None

    deadline = target_date

    def cold_window(self):
        w = self.load().get("cold_window_h") or [44, 72]
        try:
            return float(w[0]), float(w[1])
        except (TypeError, ValueError, IndexError):
            return 44.0, 72.0

    def topics(self):
        return [t for t in (self.load().get("topics") or []) if isinstance(t, dict) and t.get("id")]

    def topic(self, tid):
        for t in self.topics():
            if t["id"] == tid:
                return t
        return None

    def topic_ids(self):
        return [t["id"] for t in self.topics()]

    def require_topic(self, tid):
        t = self.topic(tid)
        if t is None:
            known = ", ".join(self.topic_ids()) or "none yet"
            raise UsageError("Unknown topic '%s' in %s. Topics: %s" % (tid, self.id, known))
        return t

    # ---- append files --------------------------------------------------------
    def load_sessions(self, include_archive=False):
        rows = self.ws.read_jsonl(self.sessions_path)
        if include_archive:
            for p in sorted(self.archive_dir.glob("sessions-*.jsonl")):
                rows = self.ws.read_jsonl(p) + rows
        return rows

    def append_session(self, row):
        return fio.append_jsonl(self.sessions_path, row)

    def load_attempts(self, include_archive=False):
        rows = []
        if include_archive:
            for p in sorted(self.archive_dir.glob("attempts-*.jsonl")):
                rows.extend(self.ws.read_jsonl(p))
        rows.extend(self.ws.read_jsonl(self.attempts_path))
        return rows

    def append_attempt(self, row):
        return fio.append_jsonl(self.attempts_path, row)

    def load_exposures(self):
        return self.ws.read_jsonl(self.exposures_path)

    def append_exposure(self, row):
        return fio.append_jsonl(self.exposures_path, row)

    def load_scan_index(self):
        return self.ws.read_jsonl(self.scans_index_path)

    def append_scan_index(self, row):
        return fio.append_jsonl(self.scans_index_path, row)

    def load_keys_opened(self):
        return self.ws.read_jsonl(self.keys_opened_path)

    def append_key_opened(self, row):
        return fio.append_jsonl(self.keys_opened_path, row)

    # ---- snapshot files --------------------------------------------------------
    def load_errors(self, include_archive=False):
        rows = []
        if include_archive:
            for p in sorted(self.archive_dir.glob("errors-*.jsonl")):
                rows.extend(self.ws.read_jsonl(p))
        rows.extend(self.ws.read_jsonl(self.errors_path))
        return rows

    def save_errors(self, rows):
        return fio.write_jsonl(self.errors_path, rows)

    def get_error(self, error_id):
        for e in self.load_errors():
            if e.get("id") == error_id:
                return e
        return None

    def load_sheets(self):
        return self.ws.read_jsonl(self.sheets_path)

    def save_sheets(self, rows):
        return fio.write_jsonl(self.sheets_path, rows)

    def get_sheet(self, sheet_id):
        for s in self.load_sheets():
            if s.get("id") == sheet_id:
                return s
        return None

    def upsert_sheet(self, row):
        """Replace the sheets row with the same id, or append it. Saves."""
        rows = self.load_sheets()
        for i, s in enumerate(rows):
            if s.get("id") == row.get("id"):
                rows[i] = row
                break
        else:
            rows.append(row)
        self.save_sheets(rows)
        return row

    def load_topics_state(self):
        data = fio.read_json(self.topics_path, default={})
        return data if isinstance(data, dict) else {}

    def save_topics_state(self, data):
        return fio.write_json(self.topics_path, data)

    def load_glossary(self):
        return self.ws.read_jsonl(self.glossary_path)

    def save_glossary(self, rows):
        return fio.write_jsonl(self.glossary_path, rows)

    # ---- session lock ----------------------------------------------------------
    def read_session_lock(self):
        if not self.session_lock_path.exists():
            return None
        try:
            data = fio.read_json(self.session_lock_path)
        except DataError:
            return {}
        return data if isinstance(data, dict) else {}

    def write_session_lock(self, data):
        return fio.write_json(self.session_lock_path, data, backup=False)

    def remove_session_lock(self):
        for p in (self.session_lock_path, self.unclosed_path):
            try:
                p.unlink()
            except OSError:
                pass

    def is_parked(self):
        return self.unclosed_path.exists()

    # ---- IDs ------------------------------------------------------------------
    def next_error_id(self, taken=None):
        """``E-<subject>-NNNN``: 1 + the max seen in errors, attempts and archive."""
        ids = _ids_in(self.load_errors(include_archive=True), "id")
        ids += _ids_in(self.load_attempts(include_archive=True), "error_id")
        if self.key_errors_dir.exists():
            ids += [p.stem for p in self.key_errors_dir.glob("E-*.json")]
        ids += list(taken or [])
        rx = r"^E-%s-(\d+)$" % re.escape(self.id)
        return "E-%s-%04d" % (self.id, max_seq(ids, rx) + 1)

    def next_session_id(self, taken=None):
        """``S-<subject>-NNNN``: 1 + the max seen in sessions, archive and the open lock."""
        ids = _ids_in(self.load_sessions(include_archive=True), "id")
        lock = self.read_session_lock() or {}
        if lock.get("session_id"):
            ids.append(lock["session_id"])
        ids += list(taken or [])
        rx = r"^S-%s-(\d+)$" % re.escape(self.id)
        return "S-%s-%04d" % (self.id, max_seq(ids, rx) + 1)


# --------------------------------------------------------------------------
# Templates and CLAUDE.md helpers
# --------------------------------------------------------------------------

def asset_text(name):
    """Text of a file in ``assets/workspace/``."""
    text = fio.read_text(WORKSPACE_ASSETS / name)
    if text is None:
        raise DataError("Missing skill asset: assets/workspace/%s" % name)
    return text


def default_config():
    import json
    return json.loads(asset_text("indelible.json"))


def default_subject():
    import json
    return json.loads(asset_text("subject.json"))


def root_subjects_section(ws):
    """The generated lines of the root CLAUDE.md: live subjects only."""
    lines = []
    for s in ws.subject_entries("live"):
        sid = s["id"]
        title, profile = sid, ""
        try:
            cfg = Subject(ws, sid, s.get("dir") or sid).load()
            title = cfg.get("title") or sid
            profile = cfg.get("profile") or ""
        except DataError:
            pass
        extra = " (%s)" % profile if profile else ""
        lines.append('- `%s`: %s%s. Folder `%s/`. Say "start %s".' % (
            sid, title, extra, s.get("dir") or sid, sid))
    if not lines:
        lines.append("(no live subjects yet)")
    return "\n".join(lines)


def update_root_claude_md(ws):
    """Rewrite the generated section of the root CLAUDE.md (if the file exists)."""
    path = ws.claude_md
    text = fio.read_text(path)
    if text is None:
        return False
    new = replace_marked_section(text, root_subjects_section(ws))
    if new != text:
        fio.write_text(path, new, backup=False)
        return True
    return False
